from __future__ import annotations

from enum import StrEnum


class TripOperationalStatus(StrEnum):
    RASCUNHO = "RASCUNHO"
    PLANEJADA = "PLANEJADA"
    AGUARDANDO_CHECKLIST = "AGUARDANDO_CHECKLIST"
    LIBERADA = "LIBERADA"
    EM_DESLOCAMENTO = "EM_DESLOCAMENTO"
    CARREGANDO = "CARREGANDO"
    EM_TRANSITO = "EM_TRANSITO"
    EM_ENTREGA = "EM_ENTREGA"
    FINALIZADA = "FINALIZADA"
    INTERROMPIDA = "INTERROMPIDA"
    CANCELADA = "CANCELADA"
