"""lote12_ia

Revision ID: 23928256fece
Revises: 28268f2461e2
Create Date: 2026-08-14 16:31:21.011754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '23928256fece'
down_revision: Union[str, None] = '28268f2461e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalias_detectadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inferencia_ia_id', sa.UUID(), nullable=False),
    sa.Column('leitura_origem_tipo', sa.String(), nullable=False),
    sa.Column('leitura_origem_id', sa.UUID(), nullable=False),
    sa.Column('nivel_confianca', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomalias_detectadas_leitura_origem', 'anomalias_detectadas', ['leitura_origem_tipo', 'leitura_origem_id'], unique=False)
    op.create_table('classificacoes_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inferencia_ia_id', sa.UUID(), nullable=False),
    sa.Column('tipo_classificacao', sa.String(), nullable=False),
    sa.Column('entidade_alvo_tipo', sa.String(), nullable=False),
    sa.Column('entidade_alvo_id', sa.UUID(), nullable=False),
    sa.Column('rotulo', sa.String(), nullable=False),
    sa.Column('nivel_confianca', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_classificacoes_ia_entidade_alvo', 'classificacoes_ia', ['entidade_alvo_tipo', 'entidade_alvo_id', 'tipo_classificacao'], unique=False)
    op.create_table('modelos_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('versao', sa.String(), nullable=False),
    sa.Column('fornecedor_logico', sa.String(), nullable=False),
    sa.Column('capacidade', sa.String(), nullable=False),
    sa.Column('contexto_maximo', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'versao', name='uq_modelos_ia_nome_versao')
    )
    op.create_table('predicoes_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inferencia_ia_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('entidade_alvo_tipo', sa.String(), nullable=False),
    sa.Column('entidade_alvo_id', sa.UUID(), nullable=False),
    sa.Column('valor_previsto', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('nivel_confianca', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_hora_validade_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predicoes_ia_entidade_alvo', 'predicoes_ia', ['entidade_alvo_tipo', 'entidade_alvo_id'], unique=False)
    op.create_index('idx_predicoes_ia_status_validade', 'predicoes_ia', ['status', 'data_hora_validade_fim'], unique=False)
    op.create_table('feedbacks_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('saida_ia_tipo', sa.String(), nullable=False),
    sa.Column('saida_ia_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.Column('justificativa', sa.String(), nullable=True),
    sa.Column('resultado_real', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedbacks_ia_saida_ia', 'feedbacks_ia', ['saida_ia_tipo', 'saida_ia_id'], unique=False)
    # `inferencias_ia` é `PARTITION BY RANGE (data_hora_inicio)` (D201, Alto volume) — SQLAlchemy
    # declarative/autogenerate não expressa particionamento Postgres nem `GENERATED` dentro de
    # `CREATE TABLE` particionado, então a tabela é criada via SQL bruto aqui, mesmo padrão de
    # `eventos_fiscais`/`heartbeats`/`viagem_status_history`/`leituras_hodometro`. Sem `UNIQUE(id)`
    # adicional (D202-style, ver `AIInferenceModel`): Postgres exige que TODA constraint `UNIQUE` de
    # uma tabela particionada inclua a coluna de partição, tornando um `UNIQUE(id)` isolado
    # impossível — as 5 tabelas dependentes referenciam `inferencia_ia_id` sem FK física por isso.
    # Uma única partição `DEFAULT` cobre qualquer `data_hora_inicio` desde já.
    op.execute(
        """
        CREATE TABLE inferencias_ia (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            modelo_ia_id UUID NOT NULL REFERENCES modelos_ia(id),
            modelo_ia_versao VARCHAR NOT NULL,
            entrada JSONB NOT NULL,
            saida JSONB,
            nivel_confianca NUMERIC(5, 2),
            data_hora_inicio TIMESTAMPTZ NOT NULL,
            data_hora_fim TIMESTAMPTZ,
            duracao_ms INTEGER GENERATED ALWAYS AS (
                EXTRACT(EPOCH FROM (data_hora_fim - data_hora_inicio)) * 1000
            ) STORED,
            custo NUMERIC(10, 4),
            numero_tentativa INTEGER NOT NULL DEFAULT 1,
            origem VARCHAR NOT NULL,
            status VARCHAR NOT NULL,
            PRIMARY KEY (id, data_hora_inicio)
        ) PARTITION BY RANGE (data_hora_inicio)
        """
    )
    op.execute("CREATE TABLE inferencias_ia_default PARTITION OF inferencias_ia DEFAULT")
    op.create_index('idx_inferencias_ia_modelo_id_criado_em', 'inferencias_ia', ['modelo_ia_id', 'data_hora_inicio'], unique=False)
    op.create_index('idx_inferencias_ia_status', 'inferencias_ia', ['tenant_id', 'status'], unique=False)
    op.create_table('leituras_visao_computacional',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inferencia_ia_id', sa.UUID(), nullable=False),
    sa.Column('arquivo_origem_id', sa.UUID(), nullable=False),
    sa.Column('tipo_leitura', sa.String(), nullable=False),
    sa.Column('regiao_analisada', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado_extraido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nivel_confianca', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revisao_humana_necessaria', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario_confirmacao_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status = 'PROCESSADA' OR revisao_humana_necessaria = FALSE OR usuario_confirmacao_id IS NOT NULL", name='ck_leituras_visao_computacional_confirmacao_humana'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_confirmacao_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugestoes_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inferencia_ia_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('entidade_alvo_tipo', sa.String(), nullable=False),
    sa.Column('entidade_alvo_id', sa.UUID(), nullable=False),
    sa.Column('recomendacao', sa.String(), nullable=False),
    sa.Column('justificativa', sa.String(), nullable=False),
    sa.Column('nivel_confianca', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario_decisao_id', sa.UUID(), nullable=True),
    sa.Column('data_hora_decisao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_decisao_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sugestoes_ia_entidade_alvo', 'sugestoes_ia', ['entidade_alvo_tipo', 'entidade_alvo_id'], unique=False)
    op.create_index('idx_sugestoes_ia_status', 'sugestoes_ia', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_sugestoes_ia_usuario_decisao_id', 'sugestoes_ia', ['usuario_decisao_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate também detectou `drop table`/`drop index` para as partições `_default` de
    # tabelas particionadas (`heartbeats`, `viagem_status_history`, `leituras_hodometro`,
    # `eventos_rastreamento`, `eventos_fiscais`, `leituras_telemetria`, `posicoes_veiculo`),
    # `logs_auditoria_default` e `spatial_ref_sys` (PostGIS) — mesmo falso positivo recorrente desde
    # o Lote 4 (D360). Removido manualmente, nenhuma dessas tabelas é tocada por esta migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sugestoes_ia_usuario_decisao_id', table_name='sugestoes_ia')
    op.drop_index('idx_sugestoes_ia_status', table_name='sugestoes_ia')
    op.drop_index('idx_sugestoes_ia_entidade_alvo', table_name='sugestoes_ia')
    op.drop_table('sugestoes_ia')
    op.drop_table('leituras_visao_computacional')
    op.drop_index('idx_inferencias_ia_status', table_name='inferencias_ia')
    op.drop_index('idx_inferencias_ia_modelo_id_criado_em', table_name='inferencias_ia')
    op.drop_table('inferencias_ia')
    op.drop_index('idx_feedbacks_ia_saida_ia', table_name='feedbacks_ia')
    op.drop_table('feedbacks_ia')
    op.drop_index('idx_predicoes_ia_status_validade', table_name='predicoes_ia')
    op.drop_index('idx_predicoes_ia_entidade_alvo', table_name='predicoes_ia')
    op.drop_table('predicoes_ia')
    op.drop_table('modelos_ia')
    op.drop_index('idx_classificacoes_ia_entidade_alvo', table_name='classificacoes_ia')
    op.drop_table('classificacoes_ia')
    op.drop_index('idx_anomalias_detectadas_leitura_origem', table_name='anomalias_detectadas')
    op.drop_table('anomalias_detectadas')
    # ### end Alembic commands ###
