"""lote11_bi_analytics_reporting

Revision ID: 28268f2461e2
Revises: de23ee6a1ffb
Create Date: 2026-08-14 14:27:33.610742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28268f2461e2'
down_revision: Union[str, None] = 'de23ee6a1ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubos_analiticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dimensoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_cubos_analiticos_tenant_id_nome')
    )
    op.create_table('metricas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('formula', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('granularidade_temporal', sa.String(), nullable=False),
    sa.Column('granularidade_dimensional', sa.String(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=False),
    sa.Column('origem_dados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('periodicidade_calculo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos_atualizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('metrica_id', sa.UUID(), nullable=True),
    sa.Column('cubo_analitico_id', sa.UUID(), nullable=True),
    sa.Column('modo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint('(metrica_id IS NOT NULL)::int + (cubo_analitico_id IS NOT NULL)::int = 1', name='ck_agendamentos_atualizacao_alvo'),
    sa.ForeignKeyConstraint(['cubo_analitico_id'], ['cubos_analiticos.id'], ),
    sa.ForeignKeyConstraint(['metrica_id'], ['metricas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cubos_analiticos_metricas',
    sa.Column('cubo_analitico_id', sa.UUID(), nullable=False),
    sa.Column('metrica_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cubo_analitico_id'], ['cubos_analiticos.id'], ),
    sa.ForeignKeyConstraint(['metrica_id'], ['metricas.id'], ),
    sa.PrimaryKeyConstraint('cubo_analitico_id', 'metrica_id')
    )
    op.create_table('dashboards_personalizados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('widgets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filtros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissoes_compartilhamento', sa.String(), nullable=False),
    sa.Column('preferencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome', name='uq_dashboards_personalizados_usuario_id_nome')
    )
    op.create_table('filtros_favoritos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('criterios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome', name='uq_filtros_favoritos_usuario_id_nome')
    )
    op.create_table('indicadores_consolidados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('metrica_id', sa.UUID(), nullable=False),
    sa.Column('metrica_versao', sa.Integer(), nullable=False),
    sa.Column('dimensao_tipo', sa.String(), nullable=False),
    sa.Column('dimensao_id', sa.UUID(), nullable=False),
    sa.Column('periodo_referencia', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_hora_calculo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['metrica_id'], ['metricas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicadores_consolidados_metrica_dimensao', 'indicadores_consolidados', ['metrica_id', 'dimensao_tipo', 'dimensao_id', 'periodo_referencia'], unique=False)
    op.create_table('relatorios_salvos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('filtros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formato_saida', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome', name='uq_relatorios_salvos_usuario_id_nome')
    )
    op.create_table('snapshots_analiticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('periodo_referencia', sa.String(), nullable=False),
    sa.Column('data_hora_consolidacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origem_processamento', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exportacoes_geradas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('relatorio_salvo_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('filtros_utilizados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('metricas_versoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('arquivo_id', sa.UUID(), nullable=True),
    sa.Column('mensagem_erro', sa.String(), nullable=True),
    sa.Column('data_hora_solicitacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['relatorio_salvo_id'], ['relatorios_salvos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exportacoes_geradas_usuario_id', 'exportacoes_geradas', ['usuario_id', 'data_hora_solicitacao'], unique=False)
    op.create_table('relatorios_salvos_metricas',
    sa.Column('relatorio_salvo_id', sa.UUID(), nullable=False),
    sa.Column('metrica_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['metrica_id'], ['metricas.id'], ),
    sa.ForeignKeyConstraint(['relatorio_salvo_id'], ['relatorios_salvos.id'], ),
    sa.PrimaryKeyConstraint('relatorio_salvo_id', 'metrica_id')
    )
    op.create_table('snapshots_analiticos_indicadores',
    sa.Column('snapshot_analitico_id', sa.UUID(), nullable=False),
    sa.Column('indicador_consolidado_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['indicador_consolidado_id'], ['indicadores_consolidados.id'], ),
    sa.ForeignKeyConstraint(['snapshot_analitico_id'], ['snapshots_analiticos.id'], ),
    sa.PrimaryKeyConstraint('snapshot_analitico_id', 'indicador_consolidado_id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate também detectou `drop table`/`drop index` para as partições `_default`
    # de tabelas particionadas (`heartbeats`, `viagem_status_history`, `leituras_hodometro`,
    # `eventos_rastreamento`, `eventos_fiscais`, `leituras_telemetria`, `posicoes_veiculo`),
    # `logs_auditoria_default` e `spatial_ref_sys` (tabela do PostGIS) — falso positivo recorrente
    # desde o Lote 4 (D360): o Alembic não entende `PARTITION BY`/extensões e acha que a partição
    # física `_default` é uma tabela nova removida. Removido manualmente, nenhuma dessas tabelas é
    # tocada por esta migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots_analiticos_indicadores')
    op.drop_table('relatorios_salvos_metricas')
    op.drop_index('idx_exportacoes_geradas_usuario_id', table_name='exportacoes_geradas')
    op.drop_table('exportacoes_geradas')
    op.drop_table('snapshots_analiticos')
    op.drop_table('relatorios_salvos')
    op.drop_index('idx_indicadores_consolidados_metrica_dimensao', table_name='indicadores_consolidados')
    op.drop_table('indicadores_consolidados')
    op.drop_table('filtros_favoritos')
    op.drop_table('dashboards_personalizados')
    op.drop_table('cubos_analiticos_metricas')
    op.drop_table('agendamentos_atualizacao')
    op.drop_table('metricas')
    op.drop_table('cubos_analiticos')
    # ### end Alembic commands ###
