"""lote8_rastreamento

Revision ID: 5bf3b459d655
Revises: e1d4dca0c7f7
Create Date: 2026-08-03 20:13:41.293797

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa

revision: str = '5bf3b459d655'
down_revision: Union[str, None] = 'e1d4dca0c7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origens_localizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('precisao_tipica_metros', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_origens_localizacao_nome')
    )
    op.create_table('provedores_rastreamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_provedores_rastreamento_tenant_id_nome')
    )
    op.create_table('cercas_eletronicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo_geometria', sa.String(), nullable=False),
    sa.Column('centro', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('raio_metros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('poligono', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("(tipo_geometria = 'CIRCULO' AND centro IS NOT NULL AND raio_metros IS NOT NULL) OR (tipo_geometria = 'POLIGONO' AND poligono IS NOT NULL)", name='ck_cercas_eletronicas_geometria'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    # `filial_id` sem FK física (D403, mesma natureza de D355) — `Filial` ainda não implementada.
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_cercas_eletronicas_tenant_id_nome')
    )
    op.create_index('idx_cercas_eletronicas_centro', 'cercas_eletronicas', ['centro'], unique=False, postgresql_using='gist', postgresql_where=sa.text('centro IS NOT NULL'))
    op.create_index('idx_cercas_eletronicas_poligono', 'cercas_eletronicas', ['poligono'], unique=False, postgresql_using='gist', postgresql_where=sa.text('poligono IS NOT NULL'))
    op.create_table('configuracoes_limite_velocidade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('categoria_veiculo_id', sa.UUID(), nullable=True),
    sa.Column('limite_kmh', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint('limite_kmh > 0', name='ck_configuracoes_limite_velocidade_limite_kmh'),
    sa.ForeignKeyConstraint(['categoria_veiculo_id'], ['categorias_veiculo.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamentos_rastreamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provedor_rastreamento_id', sa.UUID(), nullable=False),
    sa.Column('identificador_serial', sa.String(), nullable=False),
    sa.Column('tipo_equipamento', sa.String(), nullable=False),
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=True),
    sa.Column('data_inicio_vigencia', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_vigencia', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint('data_fim_vigencia IS NULL OR data_inicio_vigencia IS NULL OR data_fim_vigencia > data_inicio_vigencia', name='ck_equipamentos_rastreamento_vigencia'),
    sa.ForeignKeyConstraint(['provedor_rastreamento_id'], ['provedores_rastreamento.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_serial', name='uq_equipamentos_rastreamento_identificador_serial')
    )
    # D128 — no máximo um PRINCIPAL vigente por veículo; a Auditoria #6 do usuário testa esta
    # constraint física diretamente.
    op.create_index('uq_equipamentos_rastreamento_principal_vigente', 'equipamentos_rastreamento', ['veiculo_tracionador_id'], unique=True, postgresql_where=sa.text("tipo_equipamento = 'PRINCIPAL' AND data_fim_vigencia IS NULL"))

    # `posicoes_veiculo`/`leituras_telemetria`/`heartbeats`/`eventos_rastreamento` são Time Series de
    # alto volume (D191/D179) — SQLAlchemy autogenerate não expressa `PARTITION BY` nem `GEOGRAPHY`
    # dentro de um `CREATE TABLE` particionado, então nascem via SQL bruto, mesmo padrão de
    # `eventos_fiscais`/`viagem_status_history`/`logs_auditoria`/`leituras_hodometro`
    # (D346/D364/D383). Uma única partição DEFAULT cobre qualquer intervalo desde já. PK composta
    # `(id, <coluna_de_partição>)` — Postgres exige a coluna de partição na PK.
    op.execute(
        """
        CREATE TABLE posicoes_veiculo (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            veiculo_tracionador_id UUID NOT NULL,
            equipamento_rastreamento_id UUID NOT NULL,
            localizacao GEOGRAPHY(Point, 4326) NOT NULL,
            origem_localizacao_id UUID NOT NULL REFERENCES origens_localizacao(id),
            precisao_metros NUMERIC(6,2),
            numero_satelites SMALLINT,
            hdop NUMERIC(4,2),
            nivel_confianca NUMERIC(5,2),
            capturado_em TIMESTAMPTZ NOT NULL,
            recebido_em TIMESTAMPTZ NOT NULL,
            processado_em TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, capturado_em)
        ) PARTITION BY RANGE (capturado_em)
        """
    )
    # Sem FK física em veiculo_tracionador_id/equipamento_rastreamento_id dentro da partição —
    # mesma exceção documentada em AUDIT_MODEL.md para logs_auditoria (tabela particionada com
    # muitas partições futuras).
    op.execute("CREATE TABLE posicoes_veiculo_default PARTITION OF posicoes_veiculo DEFAULT")
    op.create_index('idx_posicoes_veiculo_veiculo_id_capturado_em', 'posicoes_veiculo', ['veiculo_tracionador_id', 'capturado_em'], unique=False)
    op.execute(
        "CREATE INDEX idx_posicoes_veiculo_localizacao ON posicoes_veiculo USING GIST (localizacao)"
    )

    op.execute(
        """
        CREATE TABLE leituras_telemetria (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            veiculo_tracionador_id UUID NOT NULL,
            equipamento_rastreamento_id UUID NOT NULL,
            posicao_veiculo_id UUID,
            tipo_sensor VARCHAR NOT NULL,
            valor NUMERIC(12,4) NOT NULL,
            unidade VARCHAR NOT NULL,
            capturado_em TIMESTAMPTZ NOT NULL,
            recebido_em TIMESTAMPTZ NOT NULL,
            processado_em TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, capturado_em)
        ) PARTITION BY RANGE (capturado_em)
        """
    )
    op.execute("CREATE TABLE leituras_telemetria_default PARTITION OF leituras_telemetria DEFAULT")
    op.create_index('idx_leituras_telemetria_veiculo_id_tipo_sensor_capturado_em', 'leituras_telemetria', ['veiculo_tracionador_id', 'tipo_sensor', 'capturado_em'], unique=False)

    op.execute(
        """
        CREATE TABLE heartbeats (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            equipamento_rastreamento_id UUID NOT NULL REFERENCES equipamentos_rastreamento(id),
            protocolo_externo VARCHAR,
            capturado_em TIMESTAMPTZ,
            recebido_em TIMESTAMPTZ NOT NULL,
            processado_em TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, recebido_em)
        ) PARTITION BY RANGE (recebido_em)
        """
    )
    # Particionada por recebido_em, não capturado_em — única exceção documentada ao padrão D191
    # (heartbeat pode não informar captura).
    op.execute("CREATE TABLE heartbeats_default PARTITION OF heartbeats DEFAULT")
    # D201/D202-style: Postgres exige que toda constraint UNIQUE de tabela particionada inclua a
    # coluna de partição — recebido_em entra por exigência do banco (mesma família de achado do
    # eventos_fiscais/uq_eventos_fiscais_documento_protocolo, Lote 7). `TrackingIngestion.
    # ingest_heartbeat` já verifica `exists_with_protocol` antes de inserir; esta é a segunda camada
    # de defesa, não a única.
    op.create_index('uq_heartbeats_equipamento_protocolo', 'heartbeats', ['equipamento_rastreamento_id', 'protocolo_externo', 'recebido_em'], unique=True, postgresql_where=sa.text('protocolo_externo IS NOT NULL'))

    op.execute(
        """
        CREATE TABLE eventos_rastreamento (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            veiculo_tracionador_id UUID NOT NULL,
            tipo VARCHAR NOT NULL,
            posicao_veiculo_id UUID,
            cerca_eletronica_id UUID REFERENCES cercas_eletronicas(id),
            configuracao_limite_velocidade_id UUID,
            valor_detectado NUMERIC(12,4),
            severidade VARCHAR NOT NULL,
            data_hora TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, data_hora)
        ) PARTITION BY RANGE (data_hora)
        """
    )
    # Derivado (D119) — particionado, mas com um único timestamp (detectado pelo sistema, não
    # capturado de fonte externa), diferente do esqueleto de três timestamps do D191.
    op.execute("CREATE TABLE eventos_rastreamento_default PARTITION OF eventos_rastreamento DEFAULT")
    op.create_index('idx_eventos_rastreamento_veiculo_id_tipo', 'eventos_rastreamento', ['veiculo_tracionador_id', 'tipo', 'data_hora'], unique=False)

    # `eventos_fiscais_default`/`viagem_status_history_default`/`logs_auditoria_default`/
    # `leituras_hodometro_default` — falso-positivo recorrente de autogenerate contra tabelas
    # particionadas já criadas em lotes anteriores (mesma causa raiz desde a Sprint 09). `spatial_ref_sys`
    # é um achado novo desta lote: tabela interna do próprio PostGIS (criada por `CREATE EXTENSION
    # postgis`, fora do `Base.metadata` da aplicação) — autogenerate propõe removê-la pelo mesmo
    # motivo (existe no banco, não existe no metadata declarado); jamais aplicado, quebraria o
    # PostGIS inteiro. Todos os cinco removidos manualmente, nunca aplicados.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (partições `_default` e `spatial_ref_sys` deliberadamente omitidas aqui também — ver nota em upgrade())
    op.drop_index('uq_heartbeats_equipamento_protocolo', table_name='heartbeats', postgresql_where=sa.text('protocolo_externo IS NOT NULL'))
    op.drop_table('heartbeats')
    op.drop_index('idx_eventos_rastreamento_veiculo_id_tipo', table_name='eventos_rastreamento')
    op.drop_table('eventos_rastreamento')
    op.drop_index('idx_leituras_telemetria_veiculo_id_tipo_sensor_capturado_em', table_name='leituras_telemetria')
    op.drop_table('leituras_telemetria')
    op.drop_index('idx_posicoes_veiculo_veiculo_id_capturado_em', table_name='posicoes_veiculo')
    op.drop_table('posicoes_veiculo')
    op.drop_index('uq_equipamentos_rastreamento_principal_vigente', table_name='equipamentos_rastreamento', postgresql_where=sa.text("tipo_equipamento = 'PRINCIPAL' AND data_fim_vigencia IS NULL"))
    op.drop_table('equipamentos_rastreamento')
    op.drop_table('configuracoes_limite_velocidade')
    op.drop_index('idx_cercas_eletronicas_poligono', table_name='cercas_eletronicas', postgresql_using='gist', postgresql_where=sa.text('poligono IS NOT NULL'))
    op.drop_index('idx_cercas_eletronicas_centro', table_name='cercas_eletronicas', postgresql_using='gist', postgresql_where=sa.text('centro IS NOT NULL'))
    op.drop_table('cercas_eletronicas')
    op.drop_table('provedores_rastreamento')
    op.drop_table('origens_localizacao')
    # ### end Alembic commands ###
