"""lote6_financeiro

Revision ID: 636bcd8e696f
Revises: 7c60098281f4
Create Date: 2026-08-03 10:38:17.278566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '636bcd8e696f'
down_revision: Union[str, None] = '7c60098281f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_bancarias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('agencia', sa.String(), nullable=False),
    sa.Column('numero_conta', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero_conta', name='uq_contas_bancarias_tenant_id_numero')
    )
    op.create_table('formas_pagamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_formas_pagamento_tenant_id_nome')
    )
    op.create_table('plano_contas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo_contabil', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('categoria_pai_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_pai_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo_contabil', name='uq_plano_contas_tenant_id_codigo')
    )
    op.create_index('idx_plano_contas_categoria_pai_id', 'plano_contas', ['categoria_pai_id'], unique=False)
    op.create_table('contas_pagar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('centro_custo_id', sa.UUID(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=True),
    sa.Column('ordem_servico_id', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('plano_contas_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("origem NOT IN ('VIAGEM', 'ORDEM_SERVICO') OR (origem = 'VIAGEM' AND viagem_id IS NOT NULL) OR (origem = 'ORDEM_SERVICO' AND ordem_servico_id IS NOT NULL)", name='ck_contas_pagar_origem_especifica'),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['plano_contas_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contas_pagar_fornecedor_id', 'contas_pagar', ['fornecedor_id'], unique=False)
    op.create_index('idx_contas_pagar_tenant_id_status', 'contas_pagar', ['tenant_id', 'status'], unique=False)
    op.create_table('aprovacoes_despesa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conta_pagar_id', sa.UUID(), nullable=False),
    sa.Column('decisao', sa.String(), nullable=False),
    sa.Column('justificativa', sa.String(), nullable=True),
    sa.Column('ator_id', sa.UUID(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['conta_pagar_id'], ['contas_pagar.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aprovacoes_despesa_tenant_id', 'aprovacoes_despesa', ['tenant_id'], unique=False)
    op.create_table('contas_pagar_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conta_pagar_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conta_pagar_id'], ['contas_pagar.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contas_pagar_status_history_tenant_id', 'contas_pagar_status_history', ['tenant_id'], unique=False)
    op.create_table('faturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('numero_fatura', sa.String(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=True),
    sa.Column('entrega_id', sa.UUID(), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('forma_pagamento_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.CheckConstraint('viagem_id IS NOT NULL OR entrega_id IS NOT NULL', name='ck_faturas_origem'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero_fatura', name='uq_faturas_tenant_id_numero')
    )
    op.create_index('idx_faturas_tenant_id_cliente_id', 'faturas', ['tenant_id', 'cliente_id'], unique=False)
    op.create_table('rateios_despesa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conta_pagar_id', sa.UUID(), nullable=False),
    sa.Column('centro_custo_id', sa.UUID(), nullable=True),
    sa.Column('viagem_id', sa.UUID(), nullable=True),
    sa.Column('criterio', sa.String(), nullable=False),
    sa.Column('valor_rateado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('centro_custo_id IS NOT NULL OR viagem_id IS NOT NULL', name='ck_rateios_despesa_alvo'),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['conta_pagar_id'], ['contas_pagar.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rateios_despesa_conta_pagar_id', 'rateios_despesa', ['conta_pagar_id'], unique=False)
    op.create_index('idx_rateios_despesa_tenant_id', 'rateios_despesa', ['tenant_id'], unique=False)
    op.create_table('contas_receber',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fatura_id', sa.UUID(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_recebimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatura_id', 'numero_parcela', name='uq_contas_receber_fatura_id_parcela')
    )
    op.create_table('contas_receber_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conta_receber_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conta_receber_id'], ['contas_receber.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contas_receber_status_history_tenant_id', 'contas_receber_status_history', ['tenant_id'], unique=False)
    op.create_table('estornos_financeiros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fatura_id', sa.UUID(), nullable=True),
    sa.Column('conta_pagar_id', sa.UUID(), nullable=True),
    sa.Column('conta_receber_id', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(fatura_id IS NOT NULL)::int + (conta_pagar_id IS NOT NULL)::int + (conta_receber_id IS NOT NULL)::int = 1', name='ck_estornos_financeiros_alvo_exclusivo'),
    sa.ForeignKeyConstraint(['conta_pagar_id'], ['contas_pagar.id'], ),
    sa.ForeignKeyConstraint(['conta_receber_id'], ['contas_receber.id'], ),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # `viagem_status_history_default`/`logs_auditoria_default`/`leituras_hodometro_default` —
    # falso-positivo recorrente de autogenerate contra tabelas particionadas (mesma causa raiz de
    # todo lote anterior desde a Sprint 09: Alembic reflete a partição `_default` do Postgres como
    # se fosse uma tabela normal a remover). Removido manualmente, nunca aplicado.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (partições `_default` deliberadamente omitidas aqui também — ver nota em upgrade())
    op.drop_table('estornos_financeiros')
    op.drop_index('idx_contas_receber_status_history_tenant_id', table_name='contas_receber_status_history')
    op.drop_table('contas_receber_status_history')
    op.drop_table('contas_receber')
    op.drop_index('idx_rateios_despesa_tenant_id', table_name='rateios_despesa')
    op.drop_index('idx_rateios_despesa_conta_pagar_id', table_name='rateios_despesa')
    op.drop_table('rateios_despesa')
    op.drop_index('idx_faturas_tenant_id_cliente_id', table_name='faturas')
    op.drop_table('faturas')
    op.drop_index('idx_contas_pagar_status_history_tenant_id', table_name='contas_pagar_status_history')
    op.drop_table('contas_pagar_status_history')
    op.drop_index('idx_aprovacoes_despesa_tenant_id', table_name='aprovacoes_despesa')
    op.drop_table('aprovacoes_despesa')
    op.drop_index('idx_contas_pagar_tenant_id_status', table_name='contas_pagar')
    op.drop_index('idx_contas_pagar_fornecedor_id', table_name='contas_pagar')
    op.drop_table('contas_pagar')
    op.drop_index('idx_plano_contas_categoria_pai_id', table_name='plano_contas')
    op.drop_table('plano_contas')
    op.drop_table('formas_pagamento')
    op.drop_table('contas_bancarias')
    # ### end Alembic commands ###
