"""operacao_viagens_entregas_ocorrencias

Revision ID: 7c60098281f4
Revises: 8d9e391e6c7a
Create Date: 2026-08-03 08:59:33.969848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7c60098281f4'
down_revision: Union[str, None] = '8d9e391e6c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entidade_tipo', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('tipo_anexo', sa.String(), nullable=False),
    sa.Column('arquivo_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anexos_entidade_tipo_entidade_id', 'anexos', ['entidade_tipo', 'entidade_id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entidade_tipo', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('visivel_cliente', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comentarios_entidade_tipo_entidade_id', 'comentarios', ['entidade_tipo', 'entidade_id'], unique=False)
    # `encerrada`/`margem_prevista` são `GENERATED ALWAYS AS (...) STORED` (D019/D185) —
    # SQLAlchemy declarative/autogenerate não expressa colunas geradas, então nascem fora da lista
    # de colunas de `create_table` e são adicionadas via SQL bruto logo abaixo (mesmo padrão já
    # usado para particionamento em `logs_auditoria`/`leituras_hodometro`, D346/D364).
    op.create_table('viagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=True),
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=True),
    sa.Column('data_programada', sa.Date(), nullable=True),
    sa.Column('janela_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_operacional', sa.String(), nullable=False),
    sa.Column('status_fiscal', sa.String(), nullable=False),
    sa.Column('status_financeiro', sa.String(), nullable=False),
    sa.Column('nome_motorista_snapshot', sa.String(), nullable=True),
    sa.Column('placa_veiculo_snapshot', sa.String(), nullable=True),
    sa.Column('cliente_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('receita_prevista_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tabela_preco_aplicada_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('custo_previsto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('custo_realizado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('receita_realizada', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margem_realizada', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('desvio_financeiro', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('km_rodado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_viagens_tenant_id_cliente_id', 'viagens', ['tenant_id', 'cliente_id'], unique=False)
    op.create_index('idx_viagens_tenant_id_data_programada', 'viagens', ['tenant_id', 'data_programada'], unique=False)
    op.create_index('idx_viagens_tenant_id_motorista_id', 'viagens', ['tenant_id', 'motorista_id'], unique=False)
    op.create_index('idx_viagens_tenant_id_status_operacional', 'viagens', ['tenant_id', 'status_operacional'], unique=False)
    op.create_index('idx_viagens_tenant_id_veiculo_id', 'viagens', ['tenant_id', 'veiculo_tracionador_id'], unique=False)
    op.execute(
        """
        ALTER TABLE viagens ADD COLUMN margem_prevista NUMERIC(14, 2) GENERATED ALWAYS AS (
            receita_prevista_snapshot - custo_previsto
        ) STORED
        """
    )
    op.execute(
        """
        ALTER TABLE viagens ADD COLUMN encerrada BOOLEAN NOT NULL GENERATED ALWAYS AS (
            status_operacional = 'FINALIZADA'
            AND status_fiscal = 'MDFE_ENCERRADO'
            AND status_financeiro = 'RECEBIDA'
        ) STORED
        """
    )
    op.create_index(
        'idx_viagens_tenant_id_encerrada', 'viagens', ['tenant_id', 'encerrada'], unique=False,
        postgresql_where=sa.text('excluido_em IS NULL'),
    )
    op.create_table('alocacoes_recurso_viagem',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=False),
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=False),
    sa.Column('implemento_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('motivo_troca', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['implemento_id'], ['implementos.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_alocacoes_recurso_viagem_vigente', 'alocacoes_recurso_viagem', ['viagem_id'], unique=True, postgresql_where=sa.text("status = 'VIGENTE'"))
    op.create_table('entregas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.String(), nullable=False),
    sa.Column('endereco_entrega', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_hora_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_recusa', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viagem_id', 'ordem', name='uq_entregas_viagem_id_ordem')
    )
    op.create_index('idx_entregas_viagem_id', 'entregas', ['viagem_id'], unique=False)
    op.create_table('ocorrencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('gravidade', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ocorrencias_tenant_id_tipo', 'ocorrencias', ['tenant_id', 'tipo'], unique=False)
    op.create_index('idx_ocorrencias_viagem_id', 'ocorrencias', ['viagem_id'], unique=False)
    # `viagem_status_history` é `PARTITION BY RANGE (data_hora)` (maior volume de transições do
    # sistema) — SQLAlchemy declarative/autogenerate não expressa particionamento Postgres, então a
    # tabela é criada via SQL bruto aqui, mesmo padrão de `logs_auditoria`/`leituras_hodometro`
    # (D346/D364). Uma única partição `DEFAULT` cobre qualquer `data_hora` desde já.
    op.execute(
        """
        CREATE TABLE viagem_status_history (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            viagem_id UUID NOT NULL REFERENCES viagens(id),
            dimensao VARCHAR NOT NULL,
            status VARCHAR NOT NULL,
            usuario_id UUID,
            origem VARCHAR NOT NULL,
            observacao VARCHAR,
            latitude FLOAT,
            longitude FLOAT,
            data_hora TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, data_hora)
        ) PARTITION BY RANGE (data_hora)
        """
    )
    op.execute("CREATE TABLE viagem_status_history_default PARTITION OF viagem_status_history DEFAULT")
    op.create_index('idx_viagem_status_history_viagem_id_dimensao', 'viagem_status_history', ['viagem_id', 'dimensao', 'data_hora'], unique=False)
    op.create_table('canhotos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entrega_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_hora_registro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinatura_arquivo_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entrega_id', name='uq_canhotos_entrega_id')
    )
    op.create_table('janelas_entrega',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entrega_id', sa.UUID(), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entrega_id', name='uq_janelas_entrega_entrega_id')
    )
    # `leituras_hodometro_default`/`logs_auditoria_default` são partições físicas reais (Lote 2/4,
    # invisíveis à ORM) — o autogenerate sempre as propõe como "removidas" por falso positivo
    # (D360); linhas removidas manualmente aqui, nunca aplicadas.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('janelas_entrega')
    op.drop_table('canhotos')
    op.drop_index('idx_viagem_status_history_viagem_id_dimensao', table_name='viagem_status_history')
    op.drop_table('viagem_status_history')
    op.drop_index('idx_ocorrencias_viagem_id', table_name='ocorrencias')
    op.drop_index('idx_ocorrencias_tenant_id_tipo', table_name='ocorrencias')
    op.drop_table('ocorrencias')
    op.drop_index('idx_entregas_viagem_id', table_name='entregas')
    op.drop_table('entregas')
    op.drop_index('uq_alocacoes_recurso_viagem_vigente', table_name='alocacoes_recurso_viagem', postgresql_where=sa.text("status = 'VIGENTE'"))
    op.drop_table('alocacoes_recurso_viagem')
    op.drop_index('idx_viagens_tenant_id_encerrada', table_name='viagens', postgresql_where=sa.text('excluido_em IS NULL'))
    op.drop_index('idx_viagens_tenant_id_veiculo_id', table_name='viagens')
    op.drop_index('idx_viagens_tenant_id_status_operacional', table_name='viagens')
    op.drop_index('idx_viagens_tenant_id_motorista_id', table_name='viagens')
    op.drop_index('idx_viagens_tenant_id_data_programada', table_name='viagens')
    op.drop_index('idx_viagens_tenant_id_cliente_id', table_name='viagens')
    op.drop_table('viagens')
    op.drop_index('idx_comentarios_entidade_tipo_entidade_id', table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index('idx_anexos_entidade_tipo_entidade_id', table_name='anexos')
    op.drop_table('anexos')
    # ### end Alembic commands ###
