"""frota veiculos implementos composicoes hodometro disponibilidade

Revision ID: 8d9e391e6c7a
Revises: a46eec036112
Create Date: 2026-08-01 19:46:03.807550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '8d9e391e6c7a'
down_revision: Union[str, None] = 'a46eec036112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_veiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_categorias_veiculo_tenant_id_nome')
    )
    op.create_table('implementos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('renavam', sa.String(), nullable=False),
    sa.Column('tipo_carroceria', sa.String(), nullable=False),
    sa.Column('categoria_veiculo_id', sa.UUID(), nullable=False),
    sa.Column('capacidade_carga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_disponibilidade', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_veiculo_id'], ['categorias_veiculo.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_implementos_tenant_id_codigo'),
    sa.UniqueConstraint('tenant_id', 'placa', name='uq_implementos_tenant_id_placa')
    )
    op.create_table('veiculos_tracionadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('renavam', sa.String(), nullable=False),
    sa.Column('fabricante', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('categoria_veiculo_id', sa.UUID(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_veiculo_id'], ['categorias_veiculo.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_veiculos_tracionadores_tenant_id_codigo'),
    sa.UniqueConstraint('tenant_id', 'placa', name='uq_veiculos_tracionadores_tenant_id_placa'),
    sa.UniqueConstraint('tenant_id', 'renavam', name='uq_veiculos_tracionadores_tenant_id_renavam')
    )
    op.create_table('composicoes_veiculares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=False),
    sa.Column('tipo_combinacao', sa.String(), nullable=False),
    sa.Column('eixos_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_inicio_vigencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim_vigencia', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alterado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint('data_fim_vigencia IS NULL OR data_fim_vigencia > data_inicio_vigencia', name='ck_composicoes_veiculares_vigencia'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_composicoes_veiculares_vigente', 'composicoes_veiculares', ['veiculo_tracionador_id'], unique=True, postgresql_where=sa.text('data_fim_vigencia IS NULL'))
    op.create_table('disponibilidade_veiculo',
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('motorista_atual_id', sa.UUID(), nullable=True),
    sa.Column('implemento_atual_id', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['implemento_atual_id'], ['implementos.id'], ),
    sa.ForeignKeyConstraint(['motorista_atual_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.PrimaryKeyConstraint('veiculo_tracionador_id')
    )
    op.create_index('idx_disponibilidade_veiculo_tenant_id', 'disponibilidade_veiculo', ['tenant_id'], unique=False)
    op.create_table('documentos_veiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('arquivo_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fichas_tecnicas_veiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=False),
    sa.Column('chassi', sa.String(), nullable=False),
    sa.Column('motor', sa.String(), nullable=True),
    sa.Column('eixos', sa.Integer(), nullable=False),
    sa.Column('tara', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacidade_carga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pbt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rntrc_proprietario', sa.String(), nullable=True),
    sa.Column('combustivel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassi', name='uq_fichas_tecnicas_veiculo_chassi'),
    sa.UniqueConstraint('veiculo_tracionador_id', name='uq_fichas_tecnicas_veiculo_veiculo_id')
    )
    # `leituras_hodometro` é `PARTITION BY RANGE (data_hora)` (Time Series, D037/D050) — SQLAlchemy
    # declarative/autogenerate não expressa particionamento Postgres, então a tabela é criada via
    # SQL bruto aqui, mesmo padrão de `logs_auditoria` (Lote 2, D346). Uma única partição `DEFAULT`
    # (D364) cobre qualquer `data_hora` desde já — partições mensais explícitas ficam para quando o
    # volume justificar. `viagem_id` sem FK física: `viagens`/`freight` é Lote 5+ (D355-like).
    op.execute(
        """
        CREATE TABLE leituras_hodometro (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            veiculo_tracionador_id UUID NOT NULL REFERENCES veiculos_tracionadores(id),
            valor_km NUMERIC(10, 2) NOT NULL,
            origem VARCHAR NOT NULL,
            viagem_id UUID,
            data_hora TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (id, data_hora)
        ) PARTITION BY RANGE (data_hora)
        """
    )
    op.execute("CREATE TABLE leituras_hodometro_default PARTITION OF leituras_hodometro DEFAULT")
    op.create_index('idx_leituras_hodometro_veiculo_id_data_hora', 'leituras_hodometro', ['veiculo_tracionador_id', 'data_hora'], unique=False)
    op.create_table('composicoes_veiculares_implementos',
    sa.Column('composicao_veicular_id', sa.UUID(), nullable=False),
    sa.Column('implemento_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composicao_veicular_id'], ['composicoes_veiculares.id'], ),
    sa.ForeignKeyConstraint(['implemento_id'], ['implementos.id'], ),
    sa.PrimaryKeyConstraint('composicao_veicular_id', 'implemento_id')
    )
    # 'logs_auditoria_default' NÃO é dropada aqui — é a partição física real de `logs_auditoria`
    # (D346/D360), invisível ao SQLAlchemy declarative; o autogenerate a marcou como "removida" só
    # por isso. A linha `op.drop_table('logs_auditoria_default')` emitida pelo autogenerate foi
    # removida manualmente.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composicoes_veiculares_implementos')
    op.drop_index('idx_leituras_hodometro_veiculo_id_data_hora', table_name='leituras_hodometro')
    op.drop_table('leituras_hodometro')
    op.drop_table('fichas_tecnicas_veiculo')
    op.drop_table('documentos_veiculo')
    op.drop_index('idx_disponibilidade_veiculo_tenant_id', table_name='disponibilidade_veiculo')
    op.drop_table('disponibilidade_veiculo')
    op.drop_index('uq_composicoes_veiculares_vigente', table_name='composicoes_veiculares', postgresql_where=sa.text('data_fim_vigencia IS NULL'))
    op.drop_table('composicoes_veiculares')
    op.drop_table('veiculos_tracionadores')
    op.drop_table('implementos')
    op.drop_table('categorias_veiculo')
    # ### end Alembic commands ###
