"""cadastros clientes fornecedores motoristas funcionarios centros_custo enderecos

Revision ID: a46eec036112
Revises: fb59c453fddf
Create Date: 2026-08-01 18:31:39.915330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'a46eec036112'
down_revision: Union[str, None] = 'fb59c453fddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_custo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('codigo_contabil', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('filial_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_centros_custo_tenant_id_codigo'),
    sa.UniqueConstraint('tenant_id', 'codigo_contabil', name='uq_centros_custo_tenant_id_codigo_contabil')
    )
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('cnpj_cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cnpj_cpf', name='uq_clientes_tenant_id_cnpj_cpf'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_clientes_tenant_id_codigo')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entidade_tipo', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('tipo_endereco', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enderecos_entidade_tipo_entidade_id', 'enderecos', ['entidade_tipo', 'entidade_id'], unique=False)
    op.create_index('uq_enderecos_entidade_principal', 'enderecos', ['entidade_tipo', 'entidade_id'], unique=True, postgresql_where=sa.text("tipo_endereco = 'PRINCIPAL' AND excluido_em IS NULL"))
    op.create_table('fornecedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('tipo_principal', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cnpj', name='uq_fornecedores_tenant_id_cnpj'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_fornecedores_tenant_id_codigo')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_funcionarios_tenant_id_codigo')
    )
    op.create_table('motoristas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tipo_vinculo', sa.String(), nullable=False),
    sa.Column('status_aptidao', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_motoristas_tenant_id_codigo'),
    sa.UniqueConstraint('tenant_id', 'cpf', name='uq_motoristas_tenant_id_cpf')
    )
    op.create_table('contatos_cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_motorista',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('categoria_cnh', sa.String(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('arquivo_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("categoria_cnh IS NULL OR tipo_documento = 'CNH'", name='ck_documentos_motorista_categoria_so_cnh'),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 'logs_auditoria_default' NÃO é dropada aqui: é a partição física real de `logs_auditoria`
    # (criada via SQL bruto na migration do Lote 2, invisível ao SQLAlchemy declarative — autogenerate
    # a marca como "removida" só porque nenhum modelo ORM a declara). Dropá-la destruiria a partição
    # de auditoria real; a linha `op.drop_table('logs_auditoria_default')` que o autogenerate emitiu
    # foi removida manualmente daqui.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_motorista')
    op.drop_table('contatos_cliente')
    op.drop_table('motoristas')
    op.drop_table('funcionarios')
    op.drop_table('fornecedores')
    op.drop_index('uq_enderecos_entidade_principal', table_name='enderecos', postgresql_where=sa.text("tipo_endereco = 'PRINCIPAL' AND excluido_em IS NULL"))
    op.drop_index('idx_enderecos_entidade_tipo_entidade_id', table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_table('clientes')
    op.drop_table('centros_custo')
    # ### end Alembic commands ###
