"""lote9_mobile

Revision ID: bffdc45ca59b
Revises: 5bf3b459d655
Create Date: 2026-08-04 01:27:22.577166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bffdc45ca59b'
down_revision: Union[str, None] = '5bf3b459d655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinaturas_digitais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('documento_tipo', sa.String(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('papel_signatario', sa.String(), nullable=False),
    sa.Column('nome_signatario_informado', sa.String(), nullable=True),
    sa.Column('arquivo_id', sa.UUID(), nullable=False),
    sa.Column('capturado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assinaturas_digitais_documento', 'assinaturas_digitais', ['documento_tipo', 'documento_id'], unique=False)
    op.create_table('dispositivos_mobile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=False),
    sa.Column('identificador_dispositivo', sa.String(), nullable=False),
    sa.Column('sistema_operacional', sa.String(), nullable=False),
    sa.Column('versao_so', sa.String(), nullable=True),
    sa.Column('versao_app', sa.String(), nullable=False),
    sa.Column('token_push', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ultimo_acesso_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificador_dispositivo', name='uq_dispositivos_mobile_identificador')
    )
    op.create_table('sessoes_mobile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=False),
    sa.Column('veiculo_tracionador_id', sa.UUID(), nullable=False),
    sa.Column('dispositivo_mobile_id', sa.UUID(), nullable=False),
    sa.Column('metodo_autenticacao', sa.String(), nullable=False),
    sa.Column('token_acesso_hash', sa.String(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_expiracao_prevista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_encerramento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_encerramento', sa.String(), nullable=True),
    sa.Column('revogado_por', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_mobile_id'], ['dispositivos_mobile.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['revogado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['veiculo_tracionador_id'], ['veiculos_tracionadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # D407 — `id` nunca vem de `gen_random_uuid()` na prática: a aplicação sempre insere
    # explicitamente o mesmo valor do `Session.id` (`sessoes_acesso`) criado na mesma operação de
    # login. A ausência de `server_default` aqui é deliberada, não um esquecimento.
    op.create_index('idx_sessoes_mobile_motorista_id_status', 'sessoes_mobile', ['motorista_id', 'status'], unique=False)
    op.create_table('filas_sincronizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sessao_mobile_id', sa.UUID(), nullable=False),
    sa.Column('sequencia_local', sa.Integer(), nullable=False),
    sa.Column('tipo_comando', sa.String(), nullable=False),
    sa.Column('entidade_destino_tipo', sa.String(), nullable=False),
    sa.Column('entidade_destino_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('identificador_local_unico', sa.String(), nullable=False),
    sa.Column('numero_tentativa', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolucao_conflito', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sessao_mobile_id'], ['sessoes_mobile.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sessao_mobile_id', 'identificador_local_unico', name='uq_filas_sincronizacao_identificador_local'),
    sa.UniqueConstraint('sessao_mobile_id', 'sequencia_local', name='uq_filas_sincronizacao_sessao_sequencia')
    )
    op.create_index('idx_filas_sincronizacao_entidade_destino', 'filas_sincronizacao', ['entidade_destino_tipo', 'entidade_destino_id'], unique=False)
    op.create_table('registros_sincronizacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sessao_mobile_id', sa.UUID(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracao_ms', sa.Integer(), sa.Computed('EXTRACT(EPOCH FROM (data_hora_fim - data_hora_inicio)) * 1000', ), nullable=True),
    sa.Column('quantidade_comandos', sa.Integer(), nullable=False),
    sa.Column('quantidade_sucesso', sa.Integer(), nullable=False),
    sa.Column('quantidade_falha', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_mobile_id'], ['sessoes_mobile.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_registros_sincronizacao_sessao_mobile_id', 'registros_sincronizacao', ['sessao_mobile_id'], unique=False)

    # `leituras_telemetria_default`/`eventos_rastreamento_default`/`logs_auditoria_default`/
    # `leituras_hodometro_default`/`viagem_status_history_default`/`heartbeats_default`/
    # `posicoes_veiculo_default`/`spatial_ref_sys`/`eventos_fiscais_default` — mesmo falso-positivo
    # recorrente de autogenerate contra tabelas particionadas/extensão PostGIS já visto em todo lote
    # anterior desde a Sprint 09 (D360-family). Nenhum deles removido, nenhum aplicado.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (tabelas/índices `_default` e `spatial_ref_sys` deliberadamente omitidos aqui também — ver nota em upgrade())
    op.drop_index('idx_registros_sincronizacao_sessao_mobile_id', table_name='registros_sincronizacao')
    op.drop_table('registros_sincronizacao')
    op.drop_index('idx_filas_sincronizacao_entidade_destino', table_name='filas_sincronizacao')
    op.drop_table('filas_sincronizacao')
    op.drop_index('idx_sessoes_mobile_motorista_id_status', table_name='sessoes_mobile')
    op.drop_table('sessoes_mobile')
    op.drop_table('dispositivos_mobile')
    op.drop_index('idx_assinaturas_digitais_documento', table_name='assinaturas_digitais')
    op.drop_table('assinaturas_digitais')
    # ### end Alembic commands ###
