"""lote10_recursos_transversais

Revision ID: de23ee6a1ffb
Revises: bffdc45ca59b
Create Date: 2026-08-14 10:31:23.186367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'de23ee6a1ffb'
down_revision: Union[str, None] = 'bffdc45ca59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_integracao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('credencial_arquivo_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execucoes_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('tipo_job', sa.String(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id', 'data_hora_inicio')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome_original', sa.String(), nullable=False),
    sa.Column('tipo_mime', sa.String(), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('hash_sha256', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('arquivo_anterior_id', sa.UUID(), nullable=True),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['arquivo_anterior_id'], ['arquivos.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_arquivos_tenant_id', 'arquivos', ['tenant_id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_destinatario_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('evento_origem_tipo', sa.String(), nullable=False),
    sa.Column('entidade_tipo', sa.String(), nullable=True),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lido_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_destinatario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notificacoes_usuario_destinatario_status', 'notificacoes', ['usuario_destinatario_id', 'status', 'enviado_em'], unique=False)
    op.create_table('preferencias_notificacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'canal', name='uq_preferencias_notificacao_usuario_canal')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('configuracao_integracao_id', sa.UUID(), nullable=True),
    sa.Column('url_destino', sa.String(), nullable=False),
    sa.Column('eventos_assinados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segredo_hmac_arquivo_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['configuracao_integracao_id'], ['configuracoes_integracao.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhooks_eventos_assinados', 'webhooks', ['eventos_assinados'], unique=False, postgresql_using='gin')
    op.create_index('idx_webhooks_tenant_id_status', 'webhooks', ['tenant_id', 'status'], unique=False)

    # `viagem_status_history_default`/`logs_auditoria_default`/`eventos_rastreamento_default`/
    # `leituras_hodometro_default`/`posicoes_veiculo_default`/`heartbeats_default`/`spatial_ref_sys`/
    # `leituras_telemetria_default`/`eventos_fiscais_default` — mesmo falso-positivo recorrente de
    # autogenerate contra tabelas particionadas/extensão PostGIS já visto em todo lote anterior desde
    # a Sprint 09 (D360-family). Nenhum deles removido, nenhum aplicado.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (tabelas/índices `_default` e `spatial_ref_sys` deliberadamente omitidos aqui também — ver nota em upgrade())
    op.drop_index('idx_webhooks_tenant_id_status', table_name='webhooks')
    op.drop_index('idx_webhooks_eventos_assinados', table_name='webhooks', postgresql_using='gin')
    op.drop_table('webhooks')
    op.drop_table('preferencias_notificacao')
    op.drop_index('idx_notificacoes_usuario_destinatario_status', table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index('idx_arquivos_tenant_id', table_name='arquivos')
    op.drop_table('arquivos')
    op.drop_table('execucoes_job')
    op.drop_table('configuracoes_integracao')
    # ### end Alembic commands ###
