"""lote7_fiscal

Revision ID: e1d4dca0c7f7
Revises: 636bcd8e696f
Create Date: 2026-08-03 16:49:04.001367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'e1d4dca0c7f7'
down_revision: Union[str, None] = '636bcd8e696f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_fiscais_tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('certificado_arquivo_id', sa.UUID(), nullable=False),
    sa.Column('certificado_validade', sa.Date(), nullable=False),
    sa.Column('ambiente', sa.String(), nullable=False),
    sa.Column('regime_tributario', sa.String(), nullable=False),
    sa.Column('serie_cte', sa.String(), nullable=False),
    sa.Column('proximo_numero_cte', sa.BigInteger(), nullable=False),
    sa.Column('serie_mdfe', sa.String(), nullable=False),
    sa.Column('proximo_numero_mdfe', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_configuracoes_fiscais_tenant_id')
    )
    # `eventos_fiscais` é `PARTITION BY RANGE (data_hora_inicio)` (D179, Alto volume potencial) —
    # SQLAlchemy declarative/autogenerate não expressa particionamento Postgres nem `GENERATED`
    # dentro de `CREATE TABLE` particionado, então a tabela é criada via SQL bruto aqui, mesmo
    # padrão de `viagem_status_history`/`logs_auditoria`/`leituras_hodometro` (D346/D364/D383-ish).
    # Uma única partição `DEFAULT` cobre qualquer `data_hora_inicio` desde já.
    op.execute(
        """
        CREATE TABLE eventos_fiscais (
            id UUID NOT NULL,
            tenant_id UUID NOT NULL REFERENCES tenants(id),
            documento_tipo VARCHAR NOT NULL,
            documento_id UUID NOT NULL,
            tipo_evento VARCHAR NOT NULL,
            payload_arquivo_id UUID NOT NULL,
            protocolo_externo VARCHAR,
            data_hora_inicio TIMESTAMPTZ NOT NULL,
            data_hora_fim TIMESTAMPTZ,
            duracao_ms INTEGER GENERATED ALWAYS AS (
                EXTRACT(EPOCH FROM (data_hora_fim - data_hora_inicio)) * 1000
            ) STORED,
            numero_tentativa INTEGER NOT NULL DEFAULT 1,
            resultado VARCHAR,
            origem VARCHAR NOT NULL,
            PRIMARY KEY (id, data_hora_inicio)
        ) PARTITION BY RANGE (data_hora_inicio)
        """
    )
    op.execute("CREATE TABLE eventos_fiscais_default PARTITION OF eventos_fiscais DEFAULT")
    op.create_index('idx_eventos_fiscais_documento_tipo_documento_id', 'eventos_fiscais', ['documento_tipo', 'documento_id'], unique=False)
    # `data_hora_inicio` (coluna de partição) precisa entrar na constraint única — Postgres exige
    # isso em toda tabela particionada (D201/D202-style), segunda camada de defesa depois da
    # checagem de aplicação em `FiscalInternalTransitions`.
    op.create_index('uq_eventos_fiscais_documento_protocolo', 'eventos_fiscais', ['documento_tipo', 'documento_id', 'protocolo_externo', 'data_hora_inicio'], unique=True, postgresql_where=sa.text('protocolo_externo IS NOT NULL'))
    op.create_table('ciots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=False),
    sa.Column('codigo_ciot', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('protocolo_antt', sa.String(), nullable=True),
    sa.Column('data_hora_registro', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_ciot', name='uq_ciots_codigo_ciot')
    )
    op.create_index('uq_ciots_protocolo_antt', 'ciots', ['protocolo_antt'], unique=True, postgresql_where=sa.text('protocolo_antt IS NOT NULL'))
    op.create_table('ctes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('valor_servico', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('xml_arquivo_id', sa.UUID(), nullable=True),
    sa.Column('protocolo_sefaz', sa.String(), nullable=True),
    sa.Column('data_hora_autorizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso', name='uq_ctes_chave_acesso'),
    sa.UniqueConstraint('tenant_id', 'serie', 'numero', name='uq_ctes_tenant_id_serie_numero')
    )
    op.create_index('idx_ctes_tenant_id_status', 'ctes', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_ctes_viagem_id', 'ctes', ['viagem_id'], unique=False)
    op.create_index('uq_ctes_protocolo_sefaz', 'ctes', ['protocolo_sefaz'], unique=True, postgresql_where=sa.text('protocolo_sefaz IS NOT NULL'))
    op.create_table('mdfes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('xml_arquivo_id', sa.UUID(), nullable=True),
    sa.Column('protocolo_sefaz', sa.String(), nullable=True),
    sa.Column('data_hora_encerramento', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso', name='uq_mdfes_chave_acesso'),
    sa.UniqueConstraint('tenant_id', 'serie', 'numero', name='uq_mdfes_tenant_id_serie_numero')
    )
    op.create_index('idx_mdfes_viagem_id', 'mdfes', ['viagem_id'], unique=False)
    op.create_index('uq_mdfes_protocolo_sefaz', 'mdfes', ['protocolo_sefaz'], unique=True, postgresql_where=sa.text('protocolo_sefaz IS NOT NULL'))
    op.create_table('cartas_correcao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cte_id', sa.UUID(), nullable=False),
    sa.Column('numero_sequencial', sa.Integer(), nullable=False),
    sa.Column('texto_correcao', sa.String(), nullable=False),
    sa.Column('xml_arquivo_id', sa.UUID(), nullable=True),
    sa.Column('data_hora_envio', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cte_id'], ['ctes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cte_id', 'numero_sequencial', name='uq_cartas_correcao_cte_id_sequencial')
    )
    op.create_table('ciots_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ciot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ciot_id'], ['ciots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ciots_status_history_tenant_id', 'ciots_status_history', ['tenant_id'], unique=False)
    op.create_table('ctes_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cte_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cte_id'], ['ctes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ctes_status_history_tenant_id', 'ctes_status_history', ['tenant_id'], unique=False)
    op.create_table('mdfes_ctes',
    sa.Column('mdfe_id', sa.UUID(), nullable=False),
    sa.Column('cte_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cte_id'], ['ctes.id'], ),
    sa.ForeignKeyConstraint(['mdfe_id'], ['mdfes.id'], ),
    sa.PrimaryKeyConstraint('mdfe_id', 'cte_id')
    )
    op.create_table('mdfes_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('mdfe_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mdfe_id'], ['mdfes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mdfes_status_history_tenant_id', 'mdfes_status_history', ['tenant_id'], unique=False)
    op.create_table('nfe_referenciadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cte_id', sa.UUID(), nullable=False),
    sa.Column('chave_acesso', sa.String(), nullable=False),
    sa.Column('xml_arquivo_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("chave_acesso ~ '^[0-9]{44}$'", name='ck_nfe_referenciadas_chave_44_digitos'),
    sa.ForeignKeyConstraint(['cte_id'], ['ctes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nfe_referenciadas_cte_id', 'nfe_referenciadas', ['cte_id'], unique=False)
    op.create_index('idx_nfe_referenciadas_tenant_id', 'nfe_referenciadas', ['tenant_id'], unique=False)
    # `logs_auditoria_default`/`leituras_hodometro_default`/`viagem_status_history_default` —
    # falso-positivo recorrente de autogenerate contra tabelas particionadas (mesma causa raiz de
    # todo lote anterior desde a Sprint 09). Removido manualmente, nunca aplicado.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (partições `_default` deliberadamente omitidas aqui também — ver nota em upgrade())
    op.drop_index('idx_nfe_referenciadas_tenant_id', table_name='nfe_referenciadas')
    op.drop_index('idx_nfe_referenciadas_cte_id', table_name='nfe_referenciadas')
    op.drop_table('nfe_referenciadas')
    op.drop_index('idx_mdfes_status_history_tenant_id', table_name='mdfes_status_history')
    op.drop_table('mdfes_status_history')
    op.drop_table('mdfes_ctes')
    op.drop_index('idx_ctes_status_history_tenant_id', table_name='ctes_status_history')
    op.drop_table('ctes_status_history')
    op.drop_index('idx_ciots_status_history_tenant_id', table_name='ciots_status_history')
    op.drop_table('ciots_status_history')
    op.drop_table('cartas_correcao')
    op.drop_index('uq_mdfes_protocolo_sefaz', table_name='mdfes', postgresql_where=sa.text('protocolo_sefaz IS NOT NULL'))
    op.drop_index('idx_mdfes_viagem_id', table_name='mdfes')
    op.drop_table('mdfes')
    op.drop_index('uq_ctes_protocolo_sefaz', table_name='ctes', postgresql_where=sa.text('protocolo_sefaz IS NOT NULL'))
    op.drop_index('idx_ctes_viagem_id', table_name='ctes')
    op.drop_index('idx_ctes_tenant_id_status', table_name='ctes')
    op.drop_table('ctes')
    op.drop_index('uq_ciots_protocolo_antt', table_name='ciots', postgresql_where=sa.text('protocolo_antt IS NOT NULL'))
    op.drop_table('ciots')
    op.drop_index('uq_eventos_fiscais_documento_protocolo', table_name='eventos_fiscais', postgresql_where=sa.text('protocolo_externo IS NOT NULL'))
    op.drop_index('idx_eventos_fiscais_documento_tipo_documento_id', table_name='eventos_fiscais')
    op.drop_table('eventos_fiscais')
    op.drop_table('configuracoes_fiscais_tenant')
    # ### end Alembic commands ###
