"""core identity tenancy audit

Revision ID: fb59c453fddf
Revises: 
Create Date: 2026-07-31 09:14:58.031792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'fb59c453fddf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # logs_auditoria é PARTITION BY RANGE (data_hora) (docs/database/relational/010-administracao.md).
    # op.create_table() não expressa particionamento declarativo do Postgres — usamos SQL bruto aqui.
    # A PK física precisa incluir a coluna de particionamento (exigência do Postgres), daí (id, data_hora)
    # em vez de só `id` — achado real do Sprint 11, Lote 2 (ver core/audit/models.py).
    # Uma única partição DEFAULT cobre todo o intervalo desde já; partições mensais/anuais explícitas
    # podem ser adicionadas depois via nova migration sem quebrar dados existentes.
    op.execute(
        """
        CREATE TABLE logs_auditoria (
            id UUID NOT NULL,
            data_hora TIMESTAMPTZ NOT NULL,
            tenant_id UUID NOT NULL,
            entidade_tipo VARCHAR NOT NULL,
            entidade_id UUID NOT NULL,
            acao VARCHAR NOT NULL,
            ator_id UUID,
            ator_nome_snapshot VARCHAR NOT NULL,
            origem VARCHAR NOT NULL,
            dados_antes JSONB,
            dados_depois JSONB,
            motivo VARCHAR,
            id_correlacao UUID NOT NULL,
            PRIMARY KEY (id, data_hora)
        ) PARTITION BY RANGE (data_hora)
        """
    )
    op.execute("CREATE TABLE logs_auditoria_default PARTITION OF logs_auditoria DEFAULT")
    op.create_table('permissoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('modulo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_permissoes_codigo')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj', name='uq_tenants_cnpj'),
    sa.UniqueConstraint('codigo', name='uq_tenants_codigo')
    )
    op.create_table('papeis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_papeis_tenant_id_nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('motorista_id', sa.UUID(), nullable=True),
    sa.Column('funcionario_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluido_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_usuarios_tenant_id_codigo'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_usuarios_tenant_id_email')
    )
    op.create_table('papel_permissao',
    sa.Column('papel_id', sa.UUID(), nullable=False),
    sa.Column('permissao_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
    sa.PrimaryKeyConstraint('papel_id', 'permissao_id')
    )
    op.create_table('sessoes_acesso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_expiracao_prevista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo_encerramento', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_papeis',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('papel_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['papel_id'], ['papeis.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'papel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_papeis')
    op.drop_table('sessoes_acesso')
    op.drop_table('papel_permissao')
    op.drop_table('usuarios')
    op.drop_table('papeis')
    op.drop_table('tenants')
    op.drop_table('permissoes')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
